; ============================================================
; platformio.ini — Adaptive Smart Traffic Light (ESP32)
; FreeRTOS + Percepio TraceRecorder (Tracealyzer)
; ============================================================

[env:esp32dev]
platform   = espressif32
board      = esp32dev
framework  = arduino

upload_port = COM4

; ── Monitor ────────────────────────────────────────────────
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, send_on_enter, log2file

; ── Upload ─────────────────────────────────────────────────
upload_speed = 115200

; ── Dependencies ───────────────────────────────────────────
lib_deps =
    ; LCD I2C 16x2 (PCF8574 backpack)
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

    ; MabuTrace for easy task profiling
    mabuware/mabutrace @ ^1.0.0

; ── Build Flags ────────────────────────────────────────────
build_flags =
    -D MABUTRACE_ENABLED=1
    ; ── Multicore: gunakan kedua core ESP32 ─────────────────
    -D ARDUINO_RUNNING_CORE=1

; ── Build Type ─────────────────────────────────────────────
build_type = debug
